/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    CadastroForm: typeof import('./src/components/CadastroForm.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputComponent: typeof import('./src/components/InputComponent.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextField: typeof import('./src/components/TextField.vue')['default']
    TextFieldComponent: typeof import('./src/components/TextFieldComponent.vue')['default']
  }
}
